<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251224194647 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attached_file (id UUID NOT NULL, name VARCHAR(255) NOT NULL, hash VARCHAR(64) NOT NULL, mime_type VARCHAR(100) NOT NULL, mime_subtype VARCHAR(100) NOT NULL, size BIGINT NOT NULL, path VARCHAR(500) NOT NULL, exif JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, heavy_name VARCHAR(36) NOT NULL, permissions JSON NOT NULL, file_info JSON DEFAULT NULL, service_info JSON DEFAULT NULL, media_card_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B010289A4DBE0824 ON attached_file (heavy_name)');
        $this->addSql('CREATE INDEX IDX_B010289A2B1B1C69 ON attached_file (media_card_id)');
        $this->addSql('CREATE TABLE exif_data_entry (id UUID NOT NULL, sample_time DOUBLE PRECISION NOT NULL, sample_duration DOUBLE PRECISION NOT NULL, f_number DOUBLE PRECISION NOT NULL, exposure_time VARCHAR(50) NOT NULL, master_gain_adjustment DOUBLE PRECISION NOT NULL, electrical_extender_magnification INT NOT NULL, gps_version_id VARCHAR(50) NOT NULL, gps_latitude_ref VARCHAR(10) NOT NULL, gps_latitude VARCHAR(255) NOT NULL, gps_longitude_ref VARCHAR(10) NOT NULL, gps_longitude VARCHAR(255) NOT NULL, gps_time_stamp TIME(0) WITHOUT TIME ZONE NOT NULL, gps_status VARCHAR(50) NOT NULL, gps_measure_mode VARCHAR(50) NOT NULL, gps_map_datum VARCHAR(50) NOT NULL, gps_date_stamp DATE NOT NULL, white_balance VARCHAR(50) NOT NULL, date_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, heavy_name VARCHAR(36) NOT NULL, permissions JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C075CD94DBE0824 ON exif_data_entry (heavy_name)');
        $this->addSql('CREATE TABLE logfile_data_entry (id UUID NOT NULL, name VARCHAR(50) DEFAULT NULL, latitude NUMERIC(10, 8) NOT NULL, longitude NUMERIC(11, 8) NOT NULL, speed DOUBLE PRECISION DEFAULT NULL, utc_time TIME(0) WITHOUT TIME ZONE NOT NULL, gps_quality_indicator SMALLINT NOT NULL, number_of_satellites SMALLINT DEFAULT NULL, hdop DOUBLE PRECISION DEFAULT NULL, altitude INT DEFAULT NULL, altitude_units VARCHAR(1) DEFAULT NULL, status VARCHAR(1) NOT NULL, date DATE NOT NULL, checksum VARCHAR(50) DEFAULT NULL, magnetic_variation DOUBLE PRECISION DEFAULT NULL, magnetic_variation_direction VARCHAR(1) DEFAULT NULL, mode_indicator VARCHAR(1) DEFAULT NULL, heavy_name VARCHAR(36) NOT NULL, permissions JSON NOT NULL, media_card_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E653E6804DBE0824 ON logfile_data_entry (heavy_name)');
        $this->addSql('CREATE INDEX IDX_E653E6802B1B1C69 ON logfile_data_entry (media_card_id)');
        $this->addSql('CREATE TABLE media_card (id UUID NOT NULL, media_id VARCHAR(50) NOT NULL, media_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, system_id VARCHAR(50) NOT NULL, system_kind VARCHAR(255) NOT NULL, master_version VARCHAR(50) NOT NULL, media_kind VARCHAR(255) NOT NULL, media_name VARCHAR(255) NOT NULL, contents JSON NOT NULL, heavy_name VARCHAR(36) NOT NULL, permissions JSON NOT NULL, name VARCHAR(255) DEFAULT NULL, trip_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D55347004DBE0824 ON media_card (heavy_name)');
        $this->addSql('CREATE INDEX IDX_D5534700A5BC2E0E ON media_card (trip_id)');
        $this->addSql('CREATE TABLE trip (id UUID NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, date_begin DATE NOT NULL, date_end DATE NOT NULL, heavy_name VARCHAR(36) NOT NULL, permissions JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7656F53B4DBE0824 ON trip (heavy_name)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE attached_file ADD CONSTRAINT FK_B010289A2B1B1C69 FOREIGN KEY (media_card_id) REFERENCES media_card (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE logfile_data_entry ADD CONSTRAINT FK_E653E6802B1B1C69 FOREIGN KEY (media_card_id) REFERENCES media_card (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_card ADD CONSTRAINT FK_D5534700A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attached_file DROP CONSTRAINT FK_B010289A2B1B1C69');
        $this->addSql('ALTER TABLE logfile_data_entry DROP CONSTRAINT FK_E653E6802B1B1C69');
        $this->addSql('ALTER TABLE media_card DROP CONSTRAINT FK_D5534700A5BC2E0E');
        $this->addSql('DROP TABLE attached_file');
        $this->addSql('DROP TABLE exif_data_entry');
        $this->addSql('DROP TABLE logfile_data_entry');
        $this->addSql('DROP TABLE media_card');
        $this->addSql('DROP TABLE trip');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
