<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251207170227 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE media_card (id UUID NOT NULL, media_id VARCHAR(50) NOT NULL, media_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, system_id VARCHAR(50) NOT NULL, system_kind VARCHAR(255) NOT NULL, master_version VARCHAR(50) NOT NULL, media_kind VARCHAR(255) NOT NULL, media_name VARCHAR(255) NOT NULL, contents JSON NOT NULL, heavy_name VARCHAR(36) NOT NULL, permissions JSON NOT NULL, trip_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D55347004DBE0824 ON media_card (heavy_name)');
        $this->addSql('CREATE INDEX IDX_D5534700A5BC2E0E ON media_card (trip_id)');
        $this->addSql('CREATE TABLE trip (id UUID NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, date_begin DATE NOT NULL, date_end DATE NOT NULL, heavy_name VARCHAR(36) NOT NULL, permissions JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7656F53B4DBE0824 ON trip (heavy_name)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE media_card ADD CONSTRAINT FK_D5534700A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE media_card DROP CONSTRAINT FK_D5534700A5BC2E0E');
        $this->addSql('DROP TABLE media_card');
        $this->addSql('DROP TABLE trip');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
